// Entry point: imports the app's own stylesheet, wires every function the
// static HTML calls via inline handlers onto `window` (ES modules don't leak
// globals the way the old classic <script> did), then boots the dashboard.
import './dashboard.css';

import { state } from './state.js';
import { initConfig } from './config.js';
import { toast } from './utils.js';
import { animateCountUp, populateYearFilter, loadVouchers, refreshStats, insertVoucherRow, handleSearch, clearSearch, spinRefresh, sortBy, setStatusFilter, clearStatusFilter } from './table.js';
import { openModal, closeModal, showQR, viewVoucher, promptRemarks, confirmRemarks, markCheckReceived, markCheckReleased, promptDelete, confirmDelete, openScanner, closeScanner, lookupManual } from './modals.js';
import { calcNet, calcDVNet, updateDVQR, promptQrBaseUrl, openCreateDV, openNewVoucher, saveVoucher, submitCreateDV, exportCreateDVExcel, exportCreateDVPDF, previewDV, exportPDF, fitPdfContentToPage } from './dvform.js';

// Warm the DV form's fallback font (Tinos) as soon as the page loads, so
// it's already cached and applied long before anyone opens Create DV,
// previews, prints, or exports a voucher — see the document.fonts.ready
// wait in exportPDF() for why this timing matters.
if (document.fonts && document.fonts.load) {
    ['400 10pt Tinos', '700 10pt Tinos', 'italic 400 10pt Tinos', 'italic 700 10pt Tinos'].forEach(f => {
        document.fonts.load(f).catch(() => {});
    });
}

// Every function referenced from an inline onclick/oninput/onchange handler
// in index.html (or in HTML generated by the table/detail renderers) must be
// reachable as a global. `currentVoucher` is exposed as a live binding so
// `onclick="previewDV(currentVoucher)"` always sees the latest voucher.
Object.assign(window, {
    openModal, closeModal,
    showQR, viewVoucher, previewDV,
    promptRemarks, confirmRemarks,
    markCheckReceived, markCheckReleased,
    promptDelete, confirmDelete,
    openScanner, closeScanner, lookupManual,
    openCreateDV, openNewVoucher, saveVoucher, submitCreateDV,
    exportCreateDVExcel, exportCreateDVPDF, exportPDF,
    calcNet, calcDVNet, updateDVQR, promptQrBaseUrl,
    loadVouchers, refreshStats, handleSearch, clearSearch, spinRefresh,
    sortBy, setStatusFilter, clearStatusFilter,
});
Object.defineProperty(window, 'currentVoucher', {
    configurable: true,
    get: () => state.currentVoucher,
    set: (v) => { state.currentVoucher = v; },
});

/* Keyboard shortcut: "/" jumps straight to search, from anywhere on the page.
   Escape closes whichever modal is currently open (using its proper close
   function — e.g. the scanner needs its camera stream stopped, not just its
   overlay hidden). */
const MODAL_CLOSE_HANDLERS = { scannerModal: closeScanner };
function closeTopModal() {
    const open = document.querySelector('.modal-overlay:not(.hidden)');
    if (!open) return false;
    (MODAL_CLOSE_HANDLERS[open.id] || (() => closeModal(open.id)))();
    return true;
}
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') { closeTopModal(); return; }
    if (e.key !== '/') return;
    const tag = (document.activeElement && document.activeElement.tagName || '').toLowerCase();
    const isTyping = tag === 'input' || tag === 'textarea' || (document.activeElement && document.activeElement.isContentEditable);
    if (isTyping) return;
    e.preventDefault();
    const el = document.getElementById('searchInput');
    if (el) { el.focus(); el.select(); }
});

// Native Ctrl+P fallback: scales #pdfContent's width and height
// independently (via transform, not a single uniform zoom) so it fills the
// print margin box exactly on both axes, right before the print dialog
// captures the page. #pdfContent is position:absolute, so this is purely
// visual and doesn't affect surrounding layout; undone afterward so the
// on-screen Preview isn't affected.
window.addEventListener('beforeprint', fitPdfContentToPage);
window.addEventListener('afterprint', () => {
    const el = document.getElementById('pdfContent');
    if (el) { el.style.zoom = 1; el.style.transform = 'none'; }
});

async function boot() {
    // Session config first: redirects to login.html on 401 before anything
    // interactive renders.
    await initConfig();

    animateCountUp();
    populateYearFilter();
    loadVouchers();

    const todayEl = document.getElementById('todayDate');
    if (todayEl) {
        todayEl.textContent = new Date().toLocaleDateString('en-PH', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
    }

    /* Floating scroll-to-top button — fades in once the page has scrolled a bit */
    const scrollTopBtn = document.getElementById('scrollTopBtn');
    if (scrollTopBtn) {
        window.addEventListener('scroll', () => {
            scrollTopBtn.classList.toggle('visible', window.scrollY > 420);
        }, { passive: true });
    }

    // If this page was opened by scanning a voucher's QR code (a link like
    // ?dv=DV-2026-0001), automatically pull that voucher up on load.
    const scannedDv = new URLSearchParams(window.location.search).get('dv');
    if (scannedDv) {
        viewVoucher(scannedDv);
    }

    // If this page was reached via the Create-DV "scan to register instantly"
    // QR — that link hits ?register=1 directly, which the backend handles and
    // redirects back here with ?registered=<DV No.>.
    const registeredRef = new URLSearchParams(window.location.search).get('registered');
    if (registeredRef) {
        window.history.replaceState({}, '', window.location.pathname);
        toast(`Voucher ${registeredRef} registered via QR scan`, 'success');
        // Pull just this one record rather than reloading the whole list.
        const isId = /^\d+$/.test(String(registeredRef));
        fetch(`/api?action=get&` + (isId ? 'id=' : 'dv=') + encodeURIComponent(registeredRef))
            .then(res => res.json())
            .then(v => { if (!v.error) { insertVoucherRow(v); refreshStats(); } })
            .catch(() => {});
        viewVoucher(registeredRef);
    }
    const registerError = new URLSearchParams(window.location.search).get('register_error');
    if (registerError) {
        window.history.replaceState({}, '', window.location.pathname);
        toast(registerError, 'error');
    }
}

boot().catch(() => { /* initConfig already redirected on 401 */ });
